/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoRouteImport } from './routes/who'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as IndexRouteImport } from './routes/index'

const WhoRoute = WhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/talk': typeof TalkRoute
  '/waiting': typeof WaitingRoute
  '/who': typeof WhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/talk': typeof TalkRoute
  '/waiting': typeof WaitingRoute
  '/who': typeof WhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/talk': typeof TalkRoute
  '/waiting': typeof WaitingRoute
  '/who': typeof WhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/summary' | '/talk' | '/waiting' | '/who'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/summary' | '/talk' | '/waiting' | '/who'
  id: '__root__' | '/' | '/summary' | '/talk' | '/waiting' | '/who'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SummaryRoute: typeof SummaryRoute
  TalkRoute: typeof TalkRoute
  WaitingRoute: typeof WaitingRoute
  WhoRoute: typeof WhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who': {
      id: '/who'
      path: '/who'
      fullPath: '/who'
      preLoaderRoute: typeof WhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SummaryRoute: SummaryRoute,
  TalkRoute: TalkRoute,
  WaitingRoute: WaitingRoute,
  WhoRoute: WhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
